[
	/*[
		"rhssaf_group_un_infantry_company_hq",
		"rhssaf_group_un_infantry_infantry_squad",
		"rhssaf_group_un_infantry_infantry_squad_sniper",
		"rhssaf_group_un_infantry_infantry_team",
		"rhssaf_group_un_infantry_infantry_team_AA",
		"rhssaf_group_un_infantry_infantry_team_heavy_at",
		"rhssaf_group_un_infantry_infantry_team_mg",
		"rhssaf_group_un_infantry_infantry_team_support",
		"rhssaf_group_un_infantry_infantry_weaponsquad",
		"rhssaf_group_un_infantry_platoon_hq"
	],*/
	[
		"rhssaf_group_army_m10_digital_company_hq",
		"rhssaf_group_army_m10_digital_infantry_squad",
		"rhssaf_group_army_m10_digital_infantry_squad_sniper",
		"rhssaf_group_army_m10_digital_infantry_team",
		"rhssaf_group_army_m10_digital_infantry_team_AA",
		"rhssaf_group_army_m10_digital_infantry_team_heavy_at",
		"rhssaf_group_army_m10_digital_infantry_team_mg",
		"rhssaf_group_army_m10_digital_infantry_team_support",
		"rhssaf_group_army_m10_digital_infantry_weaponsquad",
		"rhssaf_group_army_m10_digital_platoon_hq"
	],
	[
		"rhssaf_group_army_m93_oakleaf_company_hq",
		"rhssaf_group_army_m93_oakleaf_infantry_squad",
		"rhssaf_group_army_m93_oakleaf_infantry_squad_sniper",
		"rhssaf_group_army_m93_oakleaf_infantry_team",
		"rhssaf_group_army_m93_oakleaf_infantry_team_AA",
		"rhssaf_group_army_m93_oakleaf_infantry_team_heavy_at",
		"rhssaf_group_army_m93_oakleaf_infantry_team_mg",
		"rhssaf_group_army_m93_oakleaf_infantry_team_support",
		"rhssaf_group_army_m93_oakleaf_infantry_weaponsquad",
		"rhssaf_group_army_m93_oakleaf_platoon_hq"
	]
]
