// Custom groups can go here
[
	//Example
	/*[
		"unitClassName",
		"unitClassName",
		"unitClassName",
		"unitClassName"
	]
	[
		"unitClassName",
		"unitClassName"
	]*/
	[
		"rhsgref_cdf_b_para_squadleader",
		"rhsgref_cdf_b_para_rifleman",
		"rhsgref_cdf_b_para_machinegunner",
		"rhsgref_cdf_b_para_rifleman_lite",
		"rhsgref_cdf_b_para_marksman"
	],
	[
		"rhsgref_cdf_b_para_squadleader",
		"rhsgref_cdf_b_para_rifleman",
		"rhsgref_cdf_b_para_machinegunner",
		"rhsgref_cdf_b_para_rifleman_lite",
		"rhsgref_cdf_b_para_specialist_aa",
		"rhsgref_cdf_b_para_rifleman_lite"
	],
	[
		"rhsgref_cdf_b_para_squadleader",
		"rhsgref_cdf_b_para_marksman",
		"rhsgref_cdf_b_para_machinegunner",
		"rhsgref_cdf_b_para_machinegunner",
		"rhsgref_cdf_b_para_rifleman_lite"
	],
	[
		"rhsgref_cdf_b_para_squadleader",
		"rhsgref_cdf_b_para_rifleman",
		"rhsgref_cdf_b_para_machinegunner",
		"rhsgref_cdf_b_para_rifleman_lite",
		"rhsgref_cdf_b_para_specialist_aa"
	],
	[
		"rhsgref_cdf_b_para_officer",
		"rhsgref_cdf_b_para_rifleman",
		"rhsgref_cdf_b_para_machinegunner"
	],
	[
		"rhsgref_cdf_b_para_squadleader",
		"rhsgref_cdf_b_para_marksman",
		"rhsgref_cdf_b_para_machinegunner",
		"rhsgref_cdf_b_para_rifleman_lite",
		"rhsgref_cdf_b_para_rifleman_lite"
	]
];