[
	"rhsgref_cdf_b_btr60",
	"rhsgref_cdf_b_btr70",
	"rhsgref_cdf_b_reg_uaz_ags",
	"rhsgref_cdf_b_reg_uaz_dshkm",
	"rhsgref_cdf_b_gaz66",
	"rhsgref_cdf_b_gaz66o",
	"rhsgref_cdf_b_ural",
	"rhsgref_cdf_b_ural_open",
	"rhsgref_cdf_b_reg_uaz_open"
];