[
	"rhsusf_army_ucp_autorifleman",
	"rhsusf_army_ucp_aa",
	"rhsusf_army_ucp_autoriflemana",
	"rhsusf_army_ucp_engineer",
	"rhsusf_army_ucp_explosives",
	"rhsusf_army_ucp_grenadier",
	"rhsusf_army_ucp_javelin",
	"rhsusf_army_ucp_machinegunner",
	"rhsusf_army_ucp_marksman",
	"rhsusf_army_ucp_medic",
	"rhsusf_army_ucp_rifleman",
	"rhsusf_army_ucp_rifleman_m16",
	"rhsusf_army_ucp_rifleman_m4",
	"rhsusf_army_ucp_rifleman_m590",
	"rhsusf_army_ucp_sniper",
	"rhsusf_army_ucp_aa"
]