[
	/*[
		"rhs_group_nato_usarmy_d_company_hq",
		"rhs_group_nato_usarmy_d_infantry_squad",
		"rhs_group_nato_usarmy_d_infantry_squad_sniper",
		"rhs_group_nato_usarmy_d_infantry_team",
		"rhs_group_nato_usarmy_d_infantry_team_AA",
		"rhs_group_nato_usarmy_d_infantry_team_AT",
		"rhs_group_nato_usarmy_d_infantry_team_MG",
		"rhs_group_nato_usarmy_d_infantry_team_support",
		"rhs_group_nato_usarmy_d_infantry_weaponsquad",
		"rhs_group_nato_usarmy_d_platoon_hq"
	],*/
	[
		"rhs_group_nato_usarmy_wd_company_hq",
		"rhs_group_nato_usarmy_wd_infantry_squad",
		"rhs_group_nato_usarmy_wd_infantry_squad_sniper",
		"rhs_group_nato_usarmy_wd_infantry_team",
		"rhs_group_nato_usarmy_wd_infantry_team_AA",
		"rhs_group_nato_usarmy_wd_infantry_team_heavy_AT",
		"rhs_group_nato_usarmy_wd_infantry_team_MG",
		"rhs_group_nato_usarmy_wd_infantry_team_support",
		"rhs_group_nato_usarmy_wd_infantry_weaponsquad",
		"rhs_group_nato_usarmy_wd_platoon_hq"
	],
	/*[
		"rhs_group_nato_usmc_recon_d_infantry_team",
		"rhs_group_nato_usmc_recon_d_infantry_team_fast",
		"rhs_group_nato_usmc_recon_d_infantry_team_lite",
		"rhs_group_nato_usmc_recon_d_infantry_team_MG",
		"rhs_group_nato_usmc_recon_d_infantry_team_support"
	],*/
	[
		"rhs_group_nato_usmc_wd_infantry_squad",
		"rhs_group_nato_usmc_wd_infantry_squad_sniper",
		"rhs_group_nato_usmc_wd_infantry_team",
		"rhs_group_nato_usmc_wd_infantry_team_AA",
		"rhs_group_nato_usmc_wd_infantry_team_heavy_AT",
		"rhs_group_nato_usmc_wd_infantry_team_MG",
		"rhs_group_nato_usmc_wd_infantry_team_support",
		"rhs_group_nato_usmc_wd_infantry_weaponsquad"
	]
]
