private _name = _this select 0;
private _loc = _this select 1;
private _txt = _this select 2;
private _color = _this select 3;
private _alpha = _this select 4;
createMarker [_name, _loc];
_name setMarkerShape "ICON"; 
_name setMarkerText _txt;
_name setMarkerType "mil_triangle";
_name setMarkerColor _color;
_name setMarkerAlpha _alpha;