[
	[
		"rhs_group_rus_msv_infantry_chq",
		"rhs_group_rus_msv_infantry_fireteam",
		"rhs_group_rus_msv_infantry_MANEUVER",
		"rhs_group_rus_msv_infantry_section_AA",
		"rhs_group_rus_msv_infantry_section_AT",
		"rhs_group_rus_msv_infantry_section_marksman",
		"rhs_group_rus_msv_infantry_section_mg",
		"rhs_group_rus_msv_infantry_squad",
		"rhs_group_rus_msv_infantry_squad_2mg",
		"rhs_group_rus_msv_infantry_squad_mg_sniper",
		"rhs_group_rus_msv_infantry_squad_sniper"
	],
	/*[
		"rhs_group_rus_vdv_des_infantry_chq",
		"rhs_group_rus_vdv_des_infantry_fireteam",
		"rhs_group_rus_vdv_des_infantry_MANEUVER",
		"rhs_group_rus_vdv_des_infantry_section_AA",
		"rhs_group_rus_vdv_des_infantry_section_AT",
		"rhs_group_rus_vdv_des_infantry_section_marksman",
		"rhs_group_rus_vdv_des_infantry_section_mg",
		"rhs_group_rus_vdv_des_infantry_squad",
		"rhs_group_rus_vdv_des_infantry_squad_2mg",
		"rhs_group_rus_vdv_des_infantry_squad_mg_sniper",
		"rhs_group_rus_vdv_des_infantry_squad_sniper"
	],*/
	[
		"rhs_group_rus_vdv_infantry_chq",
		"rhs_group_rus_vdv_infantry_fireteam",
		"rhs_group_rus_vdv_infantry_MANEUVER",
		"rhs_group_rus_vdv_infantry_section_AA",
		"rhs_group_rus_vdv_infantry_section_AT",
		"rhs_group_rus_vdv_infantry_section_marksman",
		"rhs_group_rus_vdv_infantry_section_mg",
		"rhs_group_rus_vdv_infantry_squad",
		"rhs_group_rus_vdv_infantry_squad_2mg",
		"rhs_group_rus_vdv_infantry_squad_mg_sniper",
		"rhs_group_rus_vdv_infantry_squad_sniper"
	],
	[
		"rhs_group_rus_vdv_infantry_flora_chq",
		"rhs_group_rus_vdv_infantry_flora_fireteam",
		"rhs_group_rus_vdv_infantry_flora_MANEUVER",
		"rhs_group_rus_vdv_infantry_flora_section_AA",
		"rhs_group_rus_vdv_infantry_flora_section_AT",
		"rhs_group_rus_vdv_infantry_flora_section_marksman",
		"rhs_group_rus_vdv_infantry_flora_section_mg",
		"rhs_group_rus_vdv_infantry_flora_squad",
		"rhs_group_rus_vdv_infantry_flora_squad_2mg",
		"rhs_group_rus_vdv_infantry_flora_squad_mg_sniper",
		"rhs_group_rus_vdv_infantry_flora_squad_sniper"
	],
	[
		"rhs_group_rus_vdv_infantry_mflora_chq",
		"rhs_group_rus_vdv_infantry_mflora_fireteam",
		"rhs_group_rus_vdv_infantry_mflora_MANEUVER",
		"rhs_group_rus_vdv_infantry_mflora_section_AA",
		"rhs_group_rus_vdv_infantry_mflora_section_AT",
		"rhs_group_rus_vdv_infantry_mflora_section_marksman",
		"rhs_group_rus_vdv_infantry_mflora_section_mg",
		"rhs_group_rus_vdv_infantry_mflora_squad",
		"rhs_group_rus_vdv_infantry_mflora_squad_2mg",
		"rhs_group_rus_vdv_infantry_mflora_squad_mg_sniper",
		"rhs_group_rus_vdv_infantry_mflora_squad_sniper"
	],
	[
		"rhs_group_rus_vdv_infantry_recon_chq",
		"rhs_group_rus_vdv_infantry_recon_fireteam",
		"rhs_group_rus_vdv_infantry_recon_MANEUVER",
		"rhs_group_rus_vdv_infantry_recon_squad",
		"rhs_group_rus_vdv_infantry_recon_squad_2mg",
		"rhs_group_rus_vdv_infantry_recon_squad_mg_sniper",
		"rhs_group_rus_vdv_infantry_recon_squad_sniper"
	],
	[
		"rhs_group_rus_vmf_infantry_recon_chq",
		"rhs_group_rus_vmf_infantry_recon_fireteam",
		"rhs_group_rus_vmf_infantry_recon_MANEUVER",
		"rhs_group_rus_vmf_infantry_recon_squad",
		"rhs_group_rus_vmf_infantry_recon_squad_2mg",
		"rhs_group_rus_vmf_infantry_recon_squad_mg_sniper",
		"rhs_group_rus_vmf_infantry_recon_squad_sniper"
	]
];