// Custom groups can go here
[
	//Example
	/*[
		"unitClassName",
		"unitClassName",
		"unitClassName",
		"unitClassName"
	]
	[
		"unitClassName",
		"unitClassName"
	]*/
	[
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR",
		"OPTRE_Spartan2_Soldier_Rifleman_AR"
	]
];