[
	"B_Plane_CAS_01_F",
	"B_UAV_02_F",
	"B_UAV_02_CAS_F",
	//"B_T_VTOL_01_armed_F",
	"B_Plane_Fighter_01_F",
	"B_UAV_05_F",
	"B_Plane_Fighter_01_Stealth_F",
	"B_Plane_CAS_01_Cluster_F",
	"O_T_UAV_04_CAS_F"
	//"I_Plane_Fighter_04_F",
	//"O_Plane_CAS_02_F",
	//"O_T_VTOL_02_infantry_F",
	//"O_Plane_Fighter_02_F"
];